server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/order?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xue.order.pojo
#  check-config-location: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: page=page;pageSize=pageSize




logging:
  level:
    com.xue.order.dao : debug


